theme: minima
title: Ilis fancy things
author: Ilaria 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is a collection of all the fancy things that I like. These things include but are not limited to: 
  cats, fossils, crafting and food. I hope you enjoy it. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
